
platform :ios, '8.0'

inhibit_all_warnings!

pod 'AFNetworking'
pod 'SWRevealViewController'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'Toast'
pod 'JSQMessagesViewController'
pod 'MRProgress'
pod 'TSCurrencyTextField'